version: 3
currencies:
  USD:
    monetary-unit: "$"
    default: 1000.0
    max: 9999999999.0
    exchange-rate: 10000 # base currency USD, exchange rate is 10000
  EUR:
    monetary-unit: "€"
    default: 500.0
    max: 5000000000.0
    exchange-rate: 11100 # 1 EUR = 1.11 USD
  GBP:
    monetary-unit: "£"
    default: 200.0
    max: 3000000000.0
    exchange-rate: 13300 # 1 GBP = 1.33 USD
data:
  default-currency: USD
  auto-save-interval: 10 # unit: minutes
  provider: yaml # available values: yaml | sqlite | mysql
sql:
  mysql:
    host: localhost
    port: 3306
    database: economy
    username: root
    password: root123456
    table-prefix: "v1_"
